export default {
	growthRatio: 0.05,
	actions: {
		BUY_GENERATOR: 'BUY_GENERATOR',
		EXAMPLE: 'EXAMPLE_MUTATION',
		BUTTON_CLICK: 'BUTTON_CLICK',
		INCREMENT: 'INCREMENT',
		CHECK_STORY: 'CHECK_STORY'
	}
};
